# Generated by Django 4.2.3 on 2023-07-19 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0003_application_user_userschool_user'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_management.school'),
            preserve_default=False,
        ),
    ]
