# Generated by Django 4.2.3 on 2023-07-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_student_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
    ]
